"""update default values

Revision ID: b210a0b49012
Revises: e10ed610c0f6
Create Date: 2024-01-18 16:14:05.204630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b210a0b49012'
down_revision: Union[str, None] = 'e10ed610c0f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trainings', 'training_date',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_DATE'),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('trainings', 'status',
               existing_type=sa.VARCHAR(),
               server_default='Started',
               existing_nullable=True)
    op.alter_column('users', 'confirmed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('users', 'confirmed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('trainings', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('trainings', 'training_date',
               existing_type=sa.Date(),
               server_default=None,
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###
